---
fullname: Graph Theory
shortname: graph-theory
organization: coq-community
community: true
travis: true
coqdoc: false
doi: 10.1007/s10817-020-09543-2

synopsis: >-
  Graph theory results in Coq and MathComp

description: |-
  A library of formalized graph theory results, including various
  standard results from the literature (e.g., Menger’s Theorem, Hall’s
  Marriage Theorem, and the excluded minor characterization of
  treewidth-two graphs) as well as some more recent results arising
  from the study of relation algebra within the ERC CoVeCe project
  (e.g., soundness and completeness of an axiomatization of graph
  isomorphism).

publications:
- pub_url: https://hal.archives-ouvertes.fr/hal-02316859
  pub_title: Graph Theory in Coq - Minors, Treewidth, and Isomorphisms
  pub_doi: 10.1007/s10817-020-09543-2
- pub_url: https://hal.archives-ouvertes.fr/hal-02333553
  pub_title: Completeness of an Axiomatization of Graph Isomorphism via Graph Rewriting in Coq
  pub_doi: 10.1145/3372885.3373831
- pub_url: https://hal.archives-ouvertes.fr/hal-01703922
  pub_title: A Formal Proof of the Minor-Exclusion Property for Treewidth-Two Graphs
  pub_doi: 10.1007/978-3-319-94821-8_11

authors:
- name: Christian Doczkal
  initial: true
- name: Damien Pous
  initial: true

maintainers:
- name: Christian Doczkal
  nickname: chdoc
- name: Damien Pous
  nickname: damien-pous

opam-file-maintainer: christian.doczkal@inria.fr

opam-file-version: dev

license:
  fullname: CeCILL-B
  identifier: CECILL-B

supported_coq_versions:
  text: 8.10 or later
  opam: '{(>= "8.10" & < "8.13~") | (= "dev")}'

tested_coq_opam_versions:
- version: dev
- version: '8.12'
- version: '1.11.0-coq-8.11'
  repo: 'mathcomp/mathcomp'
- version: '1.11.0-coq-8.10'
  repo: 'mathcomp/mathcomp'
- version: '1.10.0-coq-8.11'
  repo: 'mathcomp/mathcomp'

dependencies:
- opam:
    name: coq-mathcomp-ssreflect
    version: '{(>= "1.10" & < "1.12~") | (= "dev")}'
  description: MathComp's SSReflect library, version 1.10 or later
- opam:
    name: coq-mathcomp-finmap
  description: MathComp's finmap library

namespace: GraphTheory

keywords:
- name: graph theory
- name: minors
- name: treewidth
- name: algebra

categories:
- name: Computer Science/Graph Theory

documentation: |-
  ## Additional Documentation
  Documentation describing the contents of the individual files is available on the [project website](https://perso.ens-lyon.fr/damien.pous/covece/graphs/)
---
